#ifndef MK1MF_BUILD
    /* auto-generated by util/mkbuildinf.pl for crypto/cversion.c */
    #define CFLAGS cflags
    /*
     * Generate CFLAGS as an array of individual characters. This is a
     * workaround for the situation where CFLAGS gets too long for a C90 string
     * literal
     */
    static const char cflags[] = {
        'c','o','m','p','i','l','e','r',':',' ','g','c','c',' ','-','I','.',' ',
        '-','I','.','.',' ','-','I','.','.','/','i','n','c','l','u','d','e',' ',
        ' ','-','D','_','F','O','R','T','I','F','Y','_','S','O','U','R','C','E',
        '=','0',' ','-','f','P','I','C',' ','-','m','6','4',' ','-','D','L','_',
        'E','N','D','I','A','N',' ','-','O','3',' ','-','W','a','l','l','\0'
    };
    #define PLATFORM "platform: linux-x86_64"
    #define DATE "built on: Wed Mar 29 18:35:00 2023"
#endif
