#include "Enclave_t.h" // Headers for trusted part (autogenerated by edger8r)
#include "sqlite3.h"
#include <string>

sqlite3* db; // Database connection object
sqlite3_stmt *replace_stmt, *begin_trans_stmt, *end_trans_stmt;
char* replace_str = "REPLACE INTO test (key, value) VALUES (?, ?)";
char* begin_trans_str = "BEGIN TRANSACTION";
char* end_trans_str = "END TRANSACTION";
sqlite3_stmt *read_stmt;
char *read_str = "SELECT * FROM test WHERE key = ?";

// SQLite callback function for printing results
static int callback(void *NotUsed, int argc, char **argv, char **azColName){
    int i;
    for(i = 0; i < argc; i++){
        std::string azColName_str = azColName[i];
        std::string argv_str = (argv[i] ? argv[i] : "NULL");
        ocall_print_string((azColName_str + " = " + argv_str + "\n").c_str());
    }
    ocall_print_string("\n");
    return 0;
}

void ecall_opendb(const char *dbname){
    int rc; // For return status of SQLite
    rc = sqlite3_open(dbname, &db); // Opening database
    if (rc) {
        ocall_println_string("SQLite error - can't open database connection: ");
        ocall_println_string(sqlite3_errmsg(db));
        return;
    }
    ocall_print_string("Enclave: Created database connection to ");
    ocall_println_string(dbname);
}

void ecall_execute_sql(const char *sql){
    int rc;
    char *zErrMsg = 0;
    rc = sqlite3_exec(db, sql, callback, 0, &zErrMsg);
    if (rc) {
        ocall_print_string("SQLite error: ");
        ocall_println_string(sqlite3_errmsg(db));
        return;
    }
}

void ecall_closedb(){
    sqlite3_close(db);
    ocall_println_string("Enclave: Closed database connection");
}

void ecall_sqlite3_prepare_v21(){
    int rc;
    char *zErrMsg = 0;
    rc = sqlite3_prepare_v2(db, replace_str, -1, &replace_stmt, NULL);
    if (rc) {
        ocall_print_string("SQLite error: ");
        ocall_println_string(sqlite3_errmsg(db));
        return;
    }
}


void ecall_sqlite3_prepare_v22(){
    int rc;
    char *zErrMsg = 0;
    rc = sqlite3_prepare_v2(db, begin_trans_str, -1, &begin_trans_stmt, NULL);
    if (rc) {
        ocall_print_string("SQLite error: ");
        ocall_println_string(sqlite3_errmsg(db));
	return;
    }
}


void ecall_sqlite3_prepare_v23(){
    int rc;
    char *zErrMsg = 0;
    rc = sqlite3_prepare_v2(db, end_trans_str, -1, &end_trans_stmt, NULL);
    if (rc) {
        ocall_print_string("SQLite error: ");
        ocall_println_string(sqlite3_errmsg(db));
	return;
    }
}

void ecall_sqlite3_prepare_v24(){
    int rc;
    char *zErrMsg = 0;
    rc = sqlite3_prepare_v2(db, read_str, -1, &read_stmt, NULL);
    if (rc) {
        ocall_print_string("SQLite error: ");
        ocall_println_string(sqlite3_errmsg(db));
	return;
    }
}



void ecall_sqlite3_step2(){
    int rc;
    char *zErrMsg = 0;
    rc = sqlite3_step(begin_trans_stmt);
    if (rc != SQLITE_DONE) {
        ocall_print_string("SQLite step2 error: ");
        ocall_println_string(sqlite3_errmsg(db));
	return;
    }
}



void ecall_sqlite3_step3(){
    int rc;
    char *zErrMsg = 0;
    rc = sqlite3_step(end_trans_stmt);
    if (rc != SQLITE_DONE) {
        ocall_print_string("SQLite step3 error: ");
        ocall_println_string(sqlite3_errmsg(db));
	return;
    }
}


void ecall_sqlite3_step1(){
    int rc;
    char *zErrMsg = 0;
    rc = sqlite3_step(replace_stmt);
    if (rc != SQLITE_DONE) {
        ocall_print_string("SQLite step1 error: ");
        ocall_println_string(sqlite3_errmsg(db));
	return;
    }
}


int ecall_sqlite3_step4(){
    int rc;
    //char *zErrMsg = 0;
    //while((rc = sqlite3_step(read_stmt)) == SQLITE_ROW){}
    rc = sqlite3_step(read_stmt);
    if(rc != SQLITE_DONE){
    	ocall_print_string("SQLite step4 error: ");
	ocall_println_string(sqlite3_errmsg(db));
	return rc;
    }

    return rc;
}



void ecall_sqlite3_clear_bindings1(){
    int rc;
    char *zErrMsg = 0;
    rc = sqlite3_clear_bindings(replace_stmt);
    if (rc) {
        ocall_print_string("SQLite error: ");
        ocall_println_string(sqlite3_errmsg(db));
	return;
    }
}


void ecall_sqlite3_clear_bindings4(){
    int rc;
    char *zErrMsg = 0;
    rc = sqlite3_clear_bindings(read_stmt);
    if (rc) {
        ocall_print_string("SQLite error: ");
        ocall_println_string(sqlite3_errmsg(db));
	return;
    }
}





void ecall_wal_checkpoint_v2(){
    int rc;
    char *zErrMsg = 0;
    rc = sqlite3_wal_checkpoint_v2(db, NULL, SQLITE_CHECKPOINT_FULL, NULL,NULL);
    if (rc) {
        ocall_print_string("SQLite error: ");
        ocall_println_string(sqlite3_errmsg(db));
	return;
    }
}

void ecall_sqlite3_finalize1(){
    int rc;
    char *zErrMsg = 0;
    rc = sqlite3_finalize(replace_stmt);
    if (rc) {
        ocall_print_string("SQLite error: ");
        ocall_println_string(sqlite3_errmsg(db));
	return;
    }
}

void ecall_sqlite3_finalize2(){
    int rc;
    char *zErrMsg = 0;
    rc = sqlite3_finalize(begin_trans_stmt);
    if (rc) {
        ocall_print_string("SQLite error: ");
        ocall_println_string(sqlite3_errmsg(db));
	return;
    }
}


void ecall_sqlite3_finalize3(){
    int rc;
    char *zErrMsg = 0;
    rc = sqlite3_finalize(end_trans_stmt);
    if (rc) {
        ocall_print_string("SQLite error: ");
        ocall_println_string(sqlite3_errmsg(db));
	return;
    }
}


void ecall_sqlite3_finalize4(){
    int rc;
    char *zErrMsg = 0;
    rc = sqlite3_finalize(read_stmt);
    if (rc) {
        ocall_print_string("SQLite error: ");
        ocall_println_string(sqlite3_errmsg(db));
	return;
    }
}



void ecall_sqlite3_reset3(){
    int rc;
    char *zErrMsg = 0;
    rc = sqlite3_reset(end_trans_stmt);
    if (rc) {
        ocall_print_string("SQLite error: ");
        ocall_println_string(sqlite3_errmsg(db));
	return;
    }
}


void ecall_sqlite3_reset4(){
    int rc;
    char *zErrMsg = 0;
    rc = sqlite3_reset(read_stmt);
    if (rc) {
        ocall_print_string("SQLite error: ");
        ocall_println_string(sqlite3_errmsg(db));
	return;
    }
}



void ecall_sqlite3_reset1(){
    int rc;
    char *zErrMsg = 0;
    rc = sqlite3_reset(replace_stmt);
    if (rc) {
        ocall_print_string("SQLite error: ");
        ocall_println_string(sqlite3_errmsg(db));
	return;
    }
}


void ecall_sqlite3_reset2(){
    int rc;
    char *zErrMsg = 0;
    rc = sqlite3_reset(begin_trans_stmt);
    if (rc) {
        ocall_print_string("SQLite error: ");
        ocall_println_string(sqlite3_errmsg(db));
	return;
    }
}


void ecall_sqlite3_bind_blob1(int i, const char* key, size_t value){
    int rc;
    char *zErrMsg = 0;
    rc = sqlite3_bind_blob(replace_stmt, i, key, value, SQLITE_STATIC);;
    if (rc) {
        ocall_print_string("SQLite error: ");
        ocall_println_string(sqlite3_errmsg(db));
	return;
    }
}




void ecall_sqlite3_bind_blob4(int i, const char* key, size_t value){
    int rc;
    char *zErrMsg = 0;
    rc = sqlite3_bind_blob(read_stmt, i, key, value, SQLITE_STATIC);;
    if (rc) {
        ocall_print_string("SQLite error: ");
        ocall_println_string(sqlite3_errmsg(db));
	return;
    }
}


